FROM nginx:1.19-alpine
LABEL maintainer "Kate-AC<alice.catharsis.kate@gmail.com>"

ENV LANG ja_JP.UTF-8

RUN apk --update add \
  bash \
  && rm -rf /var/cache/apk/*

WORK_DIR /api_gateway_emulator/scripts

COPY ./docker/conf/api_gateway_emulator/nginx.conf /etc/nginx/nginx.conf

