name: Test_and_deploy

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/**

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:60100
    steps:
    - name: Setup Node.js
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Check lint
    - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Run test
    - run: npm run test




